[package]
name = "debug_unwrap"
version = "0.0.1"
edition = "2021"
description = "Adds a debug-only version of Option::unwrap"
license = "GPL-3.0-or-later"
documentation = "https://docs.rs/debug_unwrap"
homepage = "https://lib.rs/debug_unwrap"

[dependencies]
